name : GitHub Actions Demo
on:
   push:
     branches: [main]
   pull_request:
     branches: [main]


jobs:
    build:
         ## ...
         runs-on: ubuntu-latest
         steps:

         - name: Check out the repo
           uses: actions/checkout@v3

         - name: Build the Docker image
           run: docker build . --file ./Dockerfile --tag inline_scanner_test:v1.0

         - name: lw-scanner
           run : |
            curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
            chmod +x lw-scanner
            ./lw-scanner image evaluate inline_scanner_test v1.0  --policy --fail-on-violation-exit-code 1 --save
           env:
            LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
            LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
            LW_SCANNER_DISABLE_UPDATES: true
